---
dependency:
  name: galaxy
driver:
  name: docker
scenario:
  name: default
lint:
  name: yamllint
platforms:
  - name: debian10-apache2
    image: debian:10
    command: /sbin/init
    privileged: true
provisioner:
  name: ansible
  config_options:
    defaults:
      callback_whitelist: profile_tasks
      jinja2_extensions: jinja2.ext.do
      gather_timeout: 30
      timeout: 30
    ssh_connection:
      pipelining: true
  inventory:
    group_vars:
      all:
        stage: docker
        apache2_adminhost_https: false
        apache2_extra_modules:
          - libapache2-mod-security2
  lint:
    name: ansible-lint
verifier:
  name: testinfra
  lint:
    name: flake8
