---
dependency:
  name: galaxy
driver:
  name: docker
scenario:
  name: default
platforms:
  - name: debian12-apache2
    image: debian:12
    command: /lib/systemd/systemd
    privileged: true
  - name: debian11-apache2
    image: debian:11
    command: /lib/systemd/systemd
    privileged: true
  - name: debian10-apache2
    image: debian:10
    command: /lib/systemd/systemd
    privileged: true
provisioner:
  name: ansible
  log: true
  options:
    vvv: false
  config_options:
    defaults:
      callback_whitelist: profile_tasks
      jinja2_extensions: jinja2.ext.do
      gather_timeout: 30
      timeout: 30
      verbosity: 3
  inventory:
    group_vars:
      all:
        stage: docker
        apache2_adminhost_https: false
        apache2_extra_modules:
          - libapache2-mod-security2
verifier:
  name: testinfra
