---
dependency:
  name: galaxy
driver:
  name: docker
scenario:
  name: ubuntu
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: ubuntu20-apache2
    image: ubuntu:focal
    command: /lib/systemd/systemd
    privileged: true
  - name: ubuntu18-apache2
    image: ubuntu:bionic
    command: /lib/systemd/systemd
    privileged: true
provisioner:
  name: ansible
  log: true
  options:
    vvv: true
  config_options:
    defaults:
      callback_whitelist: profile_tasks
      jinja2_extensions: jinja2.ext.do
      gather_timeout: 30
      timeout: 30
      verbosity: 3
  inventory:
    group_vars:
      all:
        stage: docker
        apache2_adminhost_https: false
        apache2_extra_modules:
          - libapache2-mod-security2
verifier:
  name: testinfra
